export const mockProfiles = [
  {
    id: '1',
    nombre: 'Ada',
    apellidos: 'Lovelace',
    foto_url: 'https://randomuser.me/api/portraits/women/1.jpg',
    organismo: 'Royal Society',
    cargo: 'Matemática y escritora',
    cv: 'Pionera de la programación, conocida por su trabajo sobre la máquina analítica de Charles Babbage.',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
  {
    id: '2',
    nombre: 'Grace',
    apellidos: 'Hopper',
    foto_url: 'https://randomuser.me/api/portraits/women/2.jpg',
    organismo: 'US Navy',
    cargo: 'Científica de la computación',
    cv: 'Desarrolladora del primer compilador y una de las figuras clave en el desarrollo de COBOL.',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
  {
    id: '3',
    nombre: 'Margaret',
    apellidos: 'Hamilton',
    foto_url: 'https://randomuser.me/api/portraits/women/3.jpg',
    organismo: 'NASA',
    cargo: 'Ingeniera de software',
    cv: 'Directora de la división de software que desarrolló el código del programa espacial Apolo.',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
    {
    id: '4',
    nombre: 'Alan',
    apellidos: 'Turing',
    foto_url: 'https://randomuser.me/api/portraits/men/4.jpg',
    organismo: 'Bletchley Park',
    cargo: 'Científico de la computación',
    cv: 'Más de 10 años de experiencia en computación teórica y criptoanálisis. Contribuciones clave al proyecto Enigma.',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
  {
    id: '5',
    nombre: 'Linus',
    apellidos: 'Torvalds',
    foto_url: 'https://randomuser.me/api/portraits/men/5.jpg',
    organismo: 'Linux Foundation',
    cargo: 'Ingeniero de software',
    cv: 'Creador y principal desarrollador del kernel de Linux y del sistema de control de versiones Git.',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
];