export const mockProfiles = [
  {
    id: '1',
    nombre: 'Ada',
    apellidos: 'Lovelace',
    foto_url: 'https://randomuser.me/api/portraits/women/1.jpg',
    organismo: 'Royal Society',
    cargo: 'Matemática y escritora',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
  {
    id: '2',
    nombre: 'Grace',
    apellidos: 'Hopper',
    foto_url: 'https://randomuser.me/api/portraits/women/2.jpg',
    organismo: 'US Navy',
    cargo: 'Científica de la computación',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
  {
    id: '3',
    nombre: 'Margaret',
    apellidos: 'Hamilton',
    foto_url: 'https://randomuser.me/api/portraits/women/3.jpg',
    organismo: 'NASA',
    cargo: 'Ingeniera de software',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
    {
    id: '4',
    nombre: 'Alan',
    apellidos: 'Turing',
    foto_url: 'https://randomuser.me/api/portraits/men/4.jpg',
    organismo: 'Bletchley Park',
    cargo: 'Científico de la computación',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
  {
    id: '5',
    nombre: 'Linus',
    apellidos: 'Torvalds',
    foto_url: 'https://randomuser.me/api/portraits/men/5.jpg',
    organismo: 'Linux Foundation',
    cargo: 'Ingeniero de software',
    linkedin_url: 'https://linkedin.com',
    github_url: 'https://github.com',
  },
];
